# This version should be updated whenever there is a change that makes this version of kani
# incomaptible with the verify-std repo.

[kani]
kani-version = "0.54.0"
commit = "e2a209bcb847803e8a5abb20ef7002b109ed0bf6"
