# This workflow is responsible for verifying the standard library with Kani.

name: Kani
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    paths:
      - 'library/**'
      - '.github/workflows/kani.yml'
      - 'scripts/check_kani.sh'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Kani does not support windows.
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            base: ubuntu
          - os: macos-latest
            base: macos
    steps:
      - name: Checkout Library
        uses: actions/checkout@v4
        with:
          path: head
          submodules: true

      - name: Run ls
        run: ls ${{github.workspace}}/head

      - name: Run Kani Script
        run: bash ./verify-rust-std/scripts/check_kani.sh ./head/
