name: Check PR Approvals

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'library/**'
      - 'doc/src/challenges/**'
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  check-approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Approvals
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.issue.number;

            const reviews = await github.rest.pulls.listReviews({
              owner,
              repo,
              pull_number
            });

            const approvers = new Set(
              reviews.data
                .filter(review => review.state === 'APPROVED')
                .map(review => review.user.login)
            );

            console.log('PR Approvers:', Array.from(approvers));

            const requiredApprovals = 2;

            if (approvers.size < requiredApprovals) {
              core.setFailed(`PR needs at least ${requiredApprovals} approvals. Current approvals: ${approvers.size}`);
            } else {
              console.log(`PR has sufficient approvals (${approvers.size}/${requiredApprovals})`);
            }
