name: PR Approval Check

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    paths:
      - 'library/**'
      - 'doc/src/challenges/**'

jobs:
  check_approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR Approvers
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            const approvers = reviews.data
              .filter(review => review.state === 'APPROVED')
              .map(review => review.user.login);

            console.log('PR Approvers:', approvers);
