# This workflow is responsible for building the standard library using the bootstrap script
# and executing the Rust regression.

name: Rust Tests
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    paths:
      - 'library/**'
      - 'rust-toolchain.toml'
      - '.github/workflows/rustc.yml'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Note windows-latest is currently failing.
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout Library
        uses: actions/checkout@v4
        with:
          path: head

      - name: Run rustc script
        run: bash ${{ github.workspace }}/scripts/check_rustc.sh ./head
